apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publish
  namespace: keda
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-client
        image: jeffhollan/rabbitmq-client:dev
        imagePullPolicy: Always
        command: ["send",  "amqp://user:PASSWORD@rabbitmq.keda.svc.cluster.local:5672", "300"]
      restartPolicy: Never
  backoffLimit: 5

